In [1]:
# Importing necessary libraries
import pandas as pd
from pandas import read_csv
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# loading dataset
filename = 'Drug.csv'
data = read_csv(filename)
data.head()

                                                Drug Disease Gender  Age
0               A CN Gel(Topical) 20gmA CN Soap 75gm    Acne   Male   23
1  A Ret 0.05% Gel 20gmA Ret 0.1% Gel 20gmA Ret 0...    Acne   Male   23
2                             ACGEL CL NANO Gel 15gm    Acne   Male   23
3                                ACGEL NANO Gel 15gm    Acne   Male   23
4                              Acleen 1% Lotion 25ml    Acne   Male   23

In [3]:
data.shape

(4955, 4)

In [4]:
data.dtypes

Drug       object
Disease    object
Gender     object
Age         int64
dtype: object

In [5]:
data['Disease'].unique()

array(['Acne', 'Allergy', 'Diabetes', 'Fungal infection',
       'Urinary tract infection', 'Malaria', 'Migraine', 'Hepatitis B',
       'AIDS'], dtype=object)

In [6]:
data.replace({'Gender': {'Female':0, 'Male':1}}, inplace=True)
data.replace({'Disease': {'Acne':0, 'Allergy':1, 'Diabetes':2, 'Fungal infection':3,
       'Urinary tract infection':4, 'Malaria':5, 'Migraine':6, 'Hepatitis B':7,
       'AIDS':8}}, inplace=True)
data.head()

C:\Users\miahm\AppData\Local\Temp\ipykernel_19548\2857723206.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.replace({'Gender': {'Female':0, 'Male':1}}, inplace=True)
C:\Users\miahm\AppData\Local\Temp\ipykernel_19548\2857723206.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.replace({'Disease': {'Acne':0, 'Allergy':1, 'Diabetes':2, 'Fungal infection':3,

                                                Drug  Disease  Gender  Age
0               A CN Gel(Topical) 20gmA CN Soap 75gm        0       1   23
1  A Ret 0.05% Gel 20gmA Ret 0.1% Gel 20gmA Ret 0...        0       1   23
2                             ACGEL CL NANO Gel 15gm        0       1   23
3                                ACGEL NANO Gel 15gm        0       1   23
4                              Acleen 1% Lotion 25ml        0       1   23

In [7]:
# Feature selection
df_x = data[['Disease', 'Gender','Age']]
df_y = data[['Drug']]

In [8]:
# Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=0)

In [9]:
# Training the model
# from sklearn.tree import DecisonTreeClassifier
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [10]:
# Decision tree
dt_classifier = tree.DecisionTreeClassifier()
dt_classifier.fit(df_x, df_y)
dt_predictions = dt_classifier.predict(X_test)
dt_accuracy = accuracy_score(y_test, dt_predictions)
print("Decision Tree Accuracy:", dt_accuracy)

Decision Tree Accuracy: 0.039354187689202826

In [11]:
# Random Forest
rf_classifier = RandomForestClassifier()
rf_classifier.fit(df_x, df_y)
rf_predictions = rf_classifier.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_predictions)
print("Random Forest Accuracy:", rf_accuracy)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Random Forest Accuracy: 0.050454086781029264

In [13]:
# Dump the model to the disk
import joblib as joblib
joblib.dump(dt_classifier, 'dt_classifier.pkl')

['dt_classifier.pkl']

In [14]:
# Loading a model to a project
loaded_dt_classifier = joblib.load('dt_classifier.pkl')

In [15]:
list_c = [5,1,60]
data_to_predict = np.array(list_c).reshape(1,-1)

In [16]:
prediction_result = loaded_dt_classifier.predict(data_to_predict)
print(prediction_result)

["Vertigil 10mg/20mg Tablet 6'S"]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(